### ISSUE TITLE
Using the pre-trained weights (ImageNet-1K) for encoder-only initialization

### ISSUE THREAD

**Issue by Nikolai10** [deep-diver/segformer-tf-transformers#11]
Hello @deep-diver, @sayakpaul, 

great job implementing Segformer in TensorFlow!

I would like to train the model from scratch, using the on the Imagenet-1K pre-trained encoder weights (https://github.com/NVlabs/SegFormer -> section Training), as described in https://arxiv.org/pdf/2105.15203.pdf (section 4.1, implementational details).

Could you please tell me briefly if this is possible and what steps are required for this?
This would be very helpful!

Thanks,
Nikolai

**Comment by sayakpaul** [comment]
We cannot provide these details, sorry. I suggest you follow the instructions and contact the SegFormer authors directly for this.
