### ISSUE TITLE
Error while creating model in TFSegFormer_Finetune.ipynb

### ISSUE THREAD

**Issue by tcw0613** [deep-diver/segformer-tf-transformers#12]
Hi @deep-diver  @sayakpaul 

I am new to image segmentation and tensorflow. Really appreciate it on implementing Segformer in TensorFlow.

I am trying to understand what's inside TFSegFormer_Finetune.ipynb. However, there was an error (shown below) while creating the model under the "Build model" section. I would appreciate it if you could assist me with this.

Thanks in advance.
Regards,
Chun Wei

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [14], in <cell line: 2>()
      1 model_checkpoint = "nvidia/mit-b0"
----> 2 model = TFSegformerForSemanticSegmentation.from_pretrained(
      3     model_checkpoint,
      4     num_labels=num_labels,
      5     id2label=id2label,
      6     label2id=label2id,
      7     ignore_mismatched_sizes=True,  # Will ensure the segmentation specific components are reinitialized.
      8 )
     10 optimizer = Adam(learning_rate=lr)
     11 model.compile(optimizer)

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\modeling_tf_utils.py:2699, in TFPreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2697         model(model.dummy_inputs)  # build the network with dummy inputs
   2698 else:
-> 2699     model(model.dummy_inputs)  # build the network with dummy inputs
   2701 # 'by_name' allow us to do transfer learning by skipping/adding layers
   2702 # see https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/python/keras/engine/network.py#L1339-L1357
   2703 try:

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\modeling_tf_utils.py:420, in unpack_inputs.<locals>.run_call_with_unpacked_inputs(self, *args, **kwargs)
    417     config = self.config
    419 unpacked_inputs = input_processing(func, config, **fn_args_and_kwargs)
--> 420 return func(self, **unpacked_inputs)

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\models\segformer\modeling_tf_segformer.py:860, in TFSegformerForSemanticSegmentation.call(self, pixel_values, labels, output_attentions, output_hidden_states, return_dict)
    855 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
    856 output_hidden_states = (
    857     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    858 )
--> 860 outputs = self.segformer(
    861     pixel_values,
    862     output_attentions=output_attentions,
    863     output_hidden_states=True,  # we need the intermediate hidden states
    864     return_dict=return_dict,
    865 )
    867 encoder_hidden_states = outputs.hidden_states if return_dict else outputs[1]
    869 logits = self.decode_head(encoder_hidden_states)

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\modeling_tf_utils.py:420, in unpack_inputs.<locals>.run_call_with_unpacked_inputs(self, *args, **kwargs)
    417     config = self.config
    419 unpacked_inputs = input_processing(func, config, **fn_args_and_kwargs)
--> 420 return func(self, **unpacked_inputs)

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\models\segformer\modeling_tf_segformer.py:482, in TFSegformerMainLayer.call(self, pixel_values, output_attentions, output_hidden_states, return_dict, training)
    477 # When running on CPU, `tf.keras.layers.Conv2D` doesn't support `NCHW` format.
    478 # So change the input format from `NCHW` to `NHWC`.
    479 # shape = (batch_size, in_height, in_width, in_channels=num_channels)
    480 pixel_values = tf.transpose(pixel_values, perm=(0, 2, 3, 1))
--> 482 encoder_outputs = self.encoder(
    483     pixel_values,
    484     output_attentions=output_attentions,
    485     output_hidden_states=output_hidden_states,
    486     return_dict=return_dict,
    487     training=training,
    488 )
    489 sequence_output = encoder_outputs[0]
    490 # Change to NCHW output format to have uniformity in the modules

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\models\segformer\modeling_tf_segformer.py:417, in TFSegformerEncoder.call(self, pixel_values, output_attentions, output_hidden_states, return_dict, training)
    415 embedding_layer, block_layer, norm_layer = x
    416 # first, obtain patch embeddings
--> 417 hidden_states, height, width = embedding_layer(hidden_states)
    419 # second, send embeddings through blocks
    420 # (each block consists of multiple layers i.e., list of layers)
    421 for i, blk in enumerate(block_layer):

File C:\ProgramData\Miniconda3\envs\segformer\lib\site-packages\transformers\models\segformer\modeling_tf_segformer.py:90, in TFSegformerOverlapPatchEmbeddings.call(self, pixel_values)
     89 def call(self, pixel_values: tf.Tensor) -> Tuple[tf.Tensor, int, int]:
---> 90     embeddings = self.proj(self.padding(pixel_values))
     91     height = shape_list(embeddings)[1]
     92     width = shape_list(embeddings)[2]

ValueError: Exception encountered when calling layer "patch_embeddings.0" "                 f"(type TFSegformerOverlapPatchEmbeddings).

Input 0 of layer "zero_padding2d" is incompatible with the layer: expected shape=(None, 128, 128, 4), found shape=(3, 512, 512, 3)

Call arguments received by layer "patch_embeddings.0" "                 f"(type TFSegformerOverlapPatchEmbeddings):
  • pixel_values=tf.Tensor(shape=(3, 512, 512, 3), dtype=float32)

**Comment by sayakpaul** [comment]
Are you using Google Colab to run the notebook?

**Comment by tcw0613** [comment]
> Are you using Google Colab to run the notebook?

I downloaded as .ipynb and run on local jupyter notebook. 

I tried to run on Google colab but I can't import transformer:
RuntimeError: Failed to import transformers.models.segformer.feature_extraction_segformer because of the following error (look up to see its traceback):
Optional[t] requires a single type. Got <module 'PIL.Image' from '/usr/local/lib/python3.7/dist-packages/PIL/Image.py'>.

**Comment by sayakpaul** [comment]
You can install transformers and then run it on Google Colab.

**Comment by tcw0613** [comment]
![image](https://user-images.githubusercontent.com/68433230/200625189-df810177-cbb1-408c-bca2-6793560da013.png)

I think I have already installed it by running the first three lines (Install necessary packages section) but the error still occurred.

**Comment by sayakpaul** [comment]
So, when you run it on Google Colab with all the dependencies installed, does it still fail?

Can you also ensure you're using the GPU runtime?

**Comment by tcw0613** [comment]
On Google Colab, it failed while importing transformer, even after I installed the dependencies. 
![image](https://user-images.githubusercontent.com/68433230/200627458-3c31e9c3-f474-4bc4-9217-4770adb1460e.png)
Yes, I have connected to GPU runtime.

**Comment by sayakpaul** [comment]
Please share a copy of your Colab Notebook that will help us reproduce the issue.

**Comment by tcw0613** [comment]
https://colab.research.google.com/drive/1F8sEY2j15K92gqpziAHSma7PLq_XiFAO?usp=sharing
I just make a copy from TFSegFormer_Finetune.ipynb and did not change anything in it.

**Comment by sayakpaul** [comment]
Please first install `transformers` (and other dependencies) before running on Colab.
